modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
issueTrackerURL="https://github.com/tlannigan/TantalusUnchained/issues" #optional
[[mods]] #mandatory
modId="tantalusunchained" #mandatory
version="1.0.0.0" #mandatory
displayName="Tantalus Unchained" #mandatory
displayURL="https://github.com/tlannigan/TantalusUnchained" #optional
credits="We'd like to thank Jesus, Baby Jesus, and Sweet Cream Butter Jesus." #optional
authors="tlannigan, Trakaa, and Scheballs" #optional
description='''
Minecraft Forge mod derived from Planetary Interactions in EVE Online.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tantalusunchained]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tantalusunchained]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"